### ISSUE TITLE
cordova.plugins.TimerPlugin.addTimeout() returns undefined?

### ISSUE THREAD

**Issue by falcofox** [schchr/cordova-plugin-timers#2]
At least in my tests I was unable to clear the timeout as addTimeout() always returns undefined and thus I cannot get the timer's ID.

**Comment by schchr** [comment]
Hello,
you need to get the id via callback, e.g.

`cordova.plugins.TimerPlugin.addTimeout(callback, duration, function(timerid){
                alert(timerid);
            });`
