### ISSUE TITLE
addInterval() ignores msInterval value

### ISSUE THREAD

**Issue by falcofox** [schchr/cordova-plugin-timers#3]
Sorry, I experienced another problem: The addInterval function ignores the msInterval value because on my Fairphone 2 (Android 5.1) the interval is executed every minute although I specified a value of 3000 (3 seconds).

**Comment by jordins** [comment]
Same here on a Samsung Galaxy s7 (Android 6.0.1)

**Comment by schchr** [comment]
I can confirm that problem. It seems that android does not allow smaller alarm intervals (<60s) any more and prolongs it to 60s (see log-cat). The only work around to build an custom interval function by recursivly using setTimeout
