### ISSUE TITLE
timers are paused when in background running on battery (android)

### ISSUE THREAD

**Issue by Mehuge** [schchr/cordova-plugin-timers#5]
Hi.  Thank you for this plugin, though I am running an old version of Cordova for Android so I lifted the code and dropped it into my existing utility plugin, as it was easier.

Have the timers working, I only needed setTimeout so only implement that, however, I was hoping this plugin would solve the issue of timers not running when the app is in background and running on battery power, but it doesn't seem to.

That is, if I set up a keepAlive in my web app, that uses utility.setTimeout (your Android alarm code) and I keep setting a new timeout each time it fires, then it will run for a while in background and then stop.  How long it runs for seems fairly random, sometimes it can run for ages, other times not.

This is because the OS has paused the app in background.

https://gist.github.com/Mehuge/dad1d66b2d70ccb5b91e7deb5855f35a

Is this what other people are seeing?

**Comment by schchr** [comment]
Hi, just for better understanding: What do you mean by "running in the backgound" exactly?
idle: screen off (and keyguard active)

- App is in the background but phone is not in idle 
- App is in the background and phone is in idle
- App is in the foreground but phone is in idle

**Comment by Mehuge** [comment]
By background I mean not in foreground, either because the screen is off or because another app is in foreground, regardless of if the phone is in use or not.  

It is only an issue when running on battery, and is then at the mercy of the OS pausing it when not in foreground.   I was hoping using the alarm service would avoid the pausing issue but in my tests it does not.

**Comment by schchr** [comment]
Thanks, I will check on it today.

**Comment by schchr** [comment]
I tested my app and I cannot confirm this issue. Maybe its caused by your android version or app configuration.

**Comment by Mehuge** [comment]
Android 5.0 and 6.0 are both affected, not sure about 4.4.  

I suspect it depends on the nature of the app, size perhaps or based on how much power the app is consuming in background.  In my case my app will sometimes keep running in background just fine other times it is paused by the OS.

Our app has been in used by customers for a few years, and it is only since they upgraded to a later version of our app that does more and will have a larger memory footprint that they started seeing the issue (their issue being that priority 0 jobs are not being delivered to devices when the app is in background for *some* devices).

The app performs a sync every 5 minutes in background, so I guess will consume a fair amount of power during that sync, and perhaps thats why the OS targets it for pausing.

I have tried so far android:persistent="true" and this plugin, neither prevent the app being paused.

Next on the list to try and solve this issue are:

- ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS
- https://github.com/katzer/cordova-plugin-background-mode
- https://developer.android.com/reference/android/os/PowerManager.html#PARTIAL_WAKE_LOCK

Anyway, its not something I expect you to fix, just wanted to report that I don't believe using alarms completely solves the problem of preventing apps being paused.
