### ISSUE TITLE
TimerPlugin addInterval error

### ISSUE THREAD

**Issue by char789** [schchr/cordova-plugin-timers#6]
Hi! I'm having difficulty in using the plugin. When I use the code below to create a clock that replaces the setInterval:

cordova.plugins.TimerPlugin.addInterval(function () { TimeInClock.updateTime(sec++); return milliseconds; }, 1000);

I keep getting this error:

Uncaught TypeError: Cannot read property 'TimerPlugin' of undefined

repeatedly... and slows down my entire app.

**Comment by srsarcasmo** [comment]
You could send the complete code, I am using in android something similar called runnable and in ios / objetive c the timer functionality
