### ISSUE TITLE
JNI ERROR (app bug): global reference table overflow (max=51200)

### ISSUE THREAD

**Issue by miketanona** [schchr/cordova-plugin-timers#7]
after 51200 calls I get JNI ERROR (app bug): global reference table overflow (max=51200) and a system reboot.

verified that deleteTimer get's called for each instance, but it down't seem to release reference.

the offending objects are 
      25219 of java.lang.ref.WeakReference (25219 unique instances)
      24117 of com.android.server.am.PendingIntentRecord (24117 unique instances)

**Comment by schchr** [comment]
thanks for your input
